cv19ResSupportV3/V3/Gateways/HelpRequestGateway.cs

This PR removes the filter on help request callbacks that restricts callbacks to those that are one day or older.
This was done as there has been a request to have callbacks available the same they they are created as there is sufficient capacity to handle these.

Ref:871961 - Remove Callback Filter

---

docker-compose.yml

Update database name to match the test db
So we can run the API locally without any problems
n/a

Fix docker-compose database name

---

.circleci/config.yml

Slight rearrangement and use `--output text` to remove the quotation marks from the output of the commands
I was poking around, playing with the AWS commandline and I found a way to remove the quotes from the output just by passing it an output option. I think it makes it a little easier to read, because you don't need to worry about the bash variable subtitution (`${PORT//\"}`)
n/a
n/a

Simplify migration script

---

cv19ResSupportV3/serverless.yml

Add security groups to development and production environments
To set up access to the RDS from lambda
To have the same set up in prod and dev
https://trello.com/c/4OvCRFPP/62-as-an-outbound-shielding-caller-i-need-to-capture-the-residents-needs-each-time-i-speak-to-them

Add security groups to development and production environments

---

cv19ResSupportV3/V3/Infrastructure/HelpRequestCallsEntity.cs
cv19ResSupportV3/V3/Infrastructure/HelpRequestsContext.cs
cv19ResSupportV3/V3/Infrastructure/Migrations/20201119115446_AddCallsTable.Designer.cs
cv19ResSupportV3/V3/Infrastructure/Migrations/20201119115446_AddCallsTable.cs

Add `help_request_calls` table using db migrations.
The table has the following columns:
- Call id - int
- Help request id - int
- Call direction/type - string
- Call outcome - string
- Time of the call - datetime
`HelpRequestId("help_request_id")` field links to the `id` in the `i_need_help_resident_support_v3` table
To provide a place where individual call attempts to the residents and their outcomes could be stored
https://trello.com/c/KFlXvf6f/56-as-an-outbound-shielding-caller-i-need-to-record-each-time-i-make-a-call-and-the-action-of-that-call

Add database migrations for a new calls table

---

cv19ResSupportV3.Tests/V3/E2ETests/GetCallbacks.cs
cv19ResSupportV3.Tests/V3/E2ETests/GetHelpRequests.cs
cv19ResSupportV3.Tests/V3/Gateways/HelpRequestCallGatewayTest.cs
cv19ResSupportV3.Tests/V3/Gateways/HelpRequestGatewayTests.cs
cv19ResSupportV3.Tests/V3/Helpers/EntityHelpers.cs
cv19ResSupportV3.Tests/V3/UseCase/GetHelpRequestUseCaseTests.cs
cv19ResSupportV3/V3/Gateways/HelpRequestGateway.cs
cv19ResSupportV3/V3/Gateways/IHelpRequestGateway.cs

Return HelpRequestCalls as part of HelpRequest for the get help request, search help request and get callbacks.
To expose information about help request calls through this API.
https://trello.com/c/olhbGBsK/86-add-api-endpoint-that-returns-all-the-calls-for-help-request
Also remove GetHelpRequests method from HelpRequestsGateway, because it wasn't being used and prevent test for duplicates from using same ID, because it keeps on failing on circleCI.
Gateway tests pass with and without: `.Include(x => x.HelpRequestCalls)`
However E2E tests require this line. Data seems to be loaded differently by entity framework for these two cases, might need further investigation.

Return calls with help request

---

cv19ResSupportV3/V3/Domain/HelpRequestCall.cs
cv19ResSupportV3/V3/Factories/HelpRequestFactory.cs
cv19ResSupportV3/V3/Infrastructure/HelpRequestCallEntity.cs
cv19ResSupportV3/V3/Infrastructure/HelpRequestsContext.cs
cv19ResSupportV3/V3/Infrastructure/Migrations/20201127151202_AddCallerToCallsTable.Designer.cs
cv19ResSupportV3/V3/Infrastructure/Migrations/20201127151202_AddCallerToCallsTable.cs
cv19ResSupportV3/V3/Infrastructure/Migrations/20201130094240_ChangeCallerToCallHandler.Designer.cs
cv19ResSupportV3/V3/Infrastructure/Migrations/20201130094240_ChangeCallerToCallHandler.cs

- Add migration to rename caller to call handler
- The caller can be the resident if its an inbound call, so a more appropriate name is call handler
N/A
https://trello.com/c/rtLti48Q/107-add-call-handler-name-to-call-on-api-and-frontend-call-log
N/A

Rename caller to call handler

---

cv19ResSupportV3/V3/Boundary/Response/HelpRequestGetResponse.cs
cv19ResSupportV3/V3/Domain/HelpRequest.cs
cv19ResSupportV3/V3/Factories/HelpRequestFactory.cs
cv19ResSupportV3/V3/Factories/ResponseFactory.cs
cv19ResSupportV3/V3/Infrastructure/HelpRequestEntity.cs
cv19ResSupportV3/V3/Infrastructure/HelpRequestsContext.cs
cv19ResSupportV3/V3/Infrastructure/Migrations/20201202103831_AddNhsCtasId.Designer.cs
cv19ResSupportV3/V3/Infrastructure/Migrations/20201202103831_AddNhsCtasId.cs

- Add nhs ctas id to api and db
- Call handlers need this to complete CTAS form for contact tracing
n/a
https://trello.com/c/PBmmLNBl/118-as-a-outbound-call-handler-when-i-view-a-help-request-then-i-can-see-the-nhs-test-and-trace-ctas-number-numbers

Add Nhs Ctsas Id

---

Makefile
cv19ResSupportV3/.config/dotnet-tools.json
cv19ResSupportV3/Startup.cs
cv19ResSupportV3/cv19ResSupportV3.csproj
cv19ResSupportV3/publish-to-swagger-hub

Introduce a script that can generate the OpenAPI documentation, via Swashbuckle and upload the documentation into Swaggerhub.
You can run the script yourself simply by running `make publish-swagger-doc`. When run it will determine which stage it is being run at, in all cases except production it will create (or update) a swagger API version based on the current version (v3.0) and the branch name.
For example, on this branch it will read `v3.0-publish-api-doc-to-swaggerhub`.
This can then be shared with others during review to ensure the API design is sane. For example, you can see the API doc generated for this branch here: https://app.swaggerhub.com/apis/Hackney/here-to-help/v3.0-publish-api-doc-to-swaggerhub
We have the ability to generate API documentation based on code, we should be …

Add script to publish API doc to Swaggerhub

---

cv19ResSupportV3/V3/Boundary/Requests/HelpRequestPatchRequest.cs
cv19ResSupportV3/V3/Boundary/Requests/HelpRequestUpdateRequest.cs
cv19ResSupportV3/V3/Boundary/Response/HelpRequestUpdateResponse.cs
cv19ResSupportV3/V3/Controllers/HelpRequestsController.cs
cv19ResSupportV3/V3/Factories/HelpRequestFactory.cs
cv19ResSupportV3/V3/Factories/ResponseFactory.cs

- Add missing Request and Response boundaries for `UpdateHelpRequest`
- Add missing Request boundary for `PatchHelpRequest`
- Add factory methods for mapping
- Return `HelpRequestGetResponse` boundary object from `get help request` path
To decouple boundaries from domain objects and enable further data structure changes
https://trello.com/c/eJV8rGEU/104-as-data-and-insight-officer-i-need-to-be-able-to-upload-a-prepared-list-of-tracing-cases-into-the-here-to-help-tool-so-that-they
Not sure about `HelpRequestUpdateResponse` could possibly reuse `HelpRequestGetResponse` or `HelpRequestCreateResponse` instead
This only adds the missing boundaries, this doesn't fix all the mappings (there is still mapping from entities to boundaries and skipping domain which needs to be fixed)
This also …

Add boundaries

---

cv19ResSupportV3.Tests/V3/E2ETests/PatchHelpRequest.cs
cv19ResSupportV3.Tests/V4/Boundary/Requests/ResidentRequestBoundaryTests.cs
cv19ResSupportV3.Tests/V4/Boundary/Responses/ResidentResponseBoundaryTests.cs
cv19ResSupportV3.Tests/V4/Controllers/ResidentsControllerTests.cs
cv19ResSupportV3.Tests/V4/E2ETests/CreateResident.cs
cv19ResSupportV3.Tests/V4/E2ETests/GetResident.cs
cv19ResSupportV3.Tests/V4/UseCases/CreateResidentUseCaseTests.cs
cv19ResSupportV3.Tests/V4/UseCases/GetResidentUseCaseTests.cs
cv19ResSupportV3.Tests/V4/UseCases/PatchResidentUseCaseTest.cs
cv19ResSupportV3/Startup.cs
cv19ResSupportV3/V3/Boundary/Requests/HelpRequestPatchRequest.cs
cv19ResSupportV3/V3/Domain/Commands/PatchResidentAndHelpRequest.cs
cv19ResSupportV3/V3/Factories/Commands/PatchHelpRequestFactory.cs
cv19ResSupportV3/V4/Boundary/Requests/ResidentRequestBoundary.cs
cv19ResSupportV3/V4/Boundary/Responses/ResidentResponseBoundary.cs
cv19ResSupportV3/V4/Controllers/ResidentsController.cs
cv19ResSupportV3/V4/Factories/ResidentFactory.cs
cv19ResSupportV3/V4/UseCase/CreateResidentsUseCase.cs
cv19ResSupportV3/V4/UseCase/GetResidentsUseCase.cs
cv19ResSupportV3/V4/UseCase/Interface/ICreateResidentsUseCase.cs
cv19ResSupportV3/V4/UseCase/Interface/IGetResidentsUseCase.cs
cv19ResSupportV3/V4/UseCase/Interface/IPatchResidentUseCase.cs
cv19ResSupportV3/V4/UseCase/PatchResidentUseCase.cs

- Added a new resident feature providing the standard REST operations:
- GET - residents (search residents)
- GET - residents/{id} (get a single resident by id)
- POST - residents (create a new resident)
- PATCH - residents/{id} (update the resident with the specified id)
- These endpoints are required to work with resident data via the API.  It is part of the new feature set that allow the saving of residents' information separate from the requests they make.
https://trello.com/c/FoIGcpjg/246-api-resident-endpoints

Resident feature

---

cv19ResSupportV3/V3/Factories/Commands/CreateHelpRequestFactory.cs
cv19ResSupportV3/V4/Factories/HelpRequestFactory.cs

- Adds a default date to help requests if none is provided.
- This is to ensure that no help request is without a creation date.

Help request default date

---

cv19ResSupportV3/V4/Controllers/ResidentHelpRequestsController.cs

- Fixed an issue where an existing help request isn't found when getting or patching an individual help request
- Individual resident help requests should be accessible from the ids provided
- The route params could not be found to pass to the use cases.  These route params needed to be explicitly identified using 
`[FromRoute(Name = "id")] int id, [FromRoute(Name = "help-request-id")] int helpRequestId` on the controllers

Resident help request fixes

---

cv19ResSupportV3/V4/Controllers/ResidentHelpRequestsController.cs
cv19ResSupportV3/V4/Factories/HelpRequestFactory.cs

- Add the mapping to calls in the resident help request response mapper
-so number of pervious calls linked to a help request can be used
https://trello.com/c/2MsJFeYV

Add calls to response mapper

---

cv19ResSupportV3.Tests/V3/E2ETests/CreateHelpRequest.cs
cv19ResSupportV3.Tests/V3/UseCase/CreateResidentUseCaseTest.cs
cv19ResSupportV3/V3/UseCase/CreateResidentUseCase.cs

Co-authored-by: Kat <katrina@madetech.com>
We need to check that the contact numbers we are concatenating are not the same when we update residents 
Previously we were not doing this, causing duplicate phone numbers being saved in our database

check phone numbers before concatenating them

---

cv19ResSupportV3.Tests/V3/E2ETests/CreateHelpRequest.cs
cv19ResSupportV3.Tests/V3/UseCase/CreateResidentUseCaseTest.cs
cv19ResSupportV3.Tests/V4/E2ETests/GetResident.cs
cv19ResSupportV3.Tests/V4/E2ETests/GetResidentHelpRequests.cs
cv19ResSupportV3/V3/UseCase/CreateResidentUseCase.cs
cv19ResSupportV3/V4/Factories/HelpRequestFactory.cs
cv19ResSupportV3/V4/Factories/ResponseFactory.cs

-Add case notes as part of the help request response
- Call handlers need an overview of case notes attached to a case
N/A
https://trello.com/c/7U4eOykz/30-as-a-call-handler-i-need-to-be-able-to-see-case-notes-for-a-resident-in-the-here-to-help-tool
Although case notes is a sub resource, it does not have its own endpoint because case notes are only needed when they are attached to a help request. Help-request requests where case notes are not required is only made once in the tool(search page), therefore a decision was made not to add a separate endpoint for a case note and instead add it to the response of a help-request request.

Add Casenotes to help requests

---

cv19ResSupportV3.Tests/V3/E2ETests/CreateHelpRequest.cs
cv19ResSupportV3.Tests/V3/UseCase/CreateResidentUseCaseTest.cs
cv19ResSupportV3/V3/UseCase/CreateResidentUseCase.cs

-Add case notes as part of the help request response
-Call handlers need an overview of case notes attached to a help request
N/A
https://trello.com/c/7U4eOykz/30-as-a-call-handler-i-need-to-be-able-to-see-case-notes-for-a-resident-in-the-here-to-help-tool
Although case notes is a sub resource, it does not have its own endpoint because case notes are only needed when they are attached to a help request. Help-request requests where case notes are not required is only made once in the tool(search page), therefore a decision was made not to add a separate endpoint for a case note and instead add it to the response of a help-request request.

Expose Casenotes as part of the HelpRequest response

---

cv19ResSupportV3.Tests/V4/Controllers/CaseNotesControllerTests.cs
cv19ResSupportV3.Tests/V4/Controllers/ResidentsControllerTests.cs
cv19ResSupportV3.Tests/V4/E2ETests/CreateCaseNote.cs
cv19ResSupportV3/V4/Boundary/Requests/CreateCaseNoteRequest.cs
cv19ResSupportV3/V4/Boundary/Responses/CaseNoteResponse.cs
cv19ResSupportV3/V4/Controllers/CaseNotesController.cs

Add create case note for a help request endpoint: POST `/api/v4/residents/1/help-requests/1/case-notes`
It takes in a JSON object containing CaseNote:
`{"CaseNote": "{\"author\":\"Test\",\"noteDate\":\"Tue, 08 Sep 2020 10:15:52 GMT\",\"note\":\"*** TESTED ***\"}"}`
CaseNote should be a JSON string containing author, noteDate, note and helpNeeded.
To create a new entry for each newly added case note
N/A
https://trello.com/c/rWjYqGL2/40-as-a-call-handler-i-need-to-be-able-to-record-case-notes-from-a-call
Might need to add another create endpoint if we want to create case notes for a resident and not a help request

Add Create CaseNote endpoint

---

cv19ResSupportV3.Tests/V3/Gateways/CaseNotesGatewayTest.cs
cv19ResSupportV3.Tests/V4/Controllers/CaseNotesControllerTests.cs
cv19ResSupportV3.Tests/V4/E2ETests/GetCaseNotesByResidentId.cs
cv19ResSupportV3.Tests/V4/Factories/CaseNotesFactoryTest.cs
cv19ResSupportV3.Tests/V4/UseCases/GetCaseNotesByResidentIdUseCaseTests.cs
cv19ResSupportV3/Startup.cs
cv19ResSupportV3/V3/Gateways/CaseNotesGateway.cs
cv19ResSupportV3/V3/Gateways/ICaseNotesGateway.cs
cv19ResSupportV3/V4/Boundary/Responses/CaseNoteResponse.cs
cv19ResSupportV3/V4/Controllers/CaseNotesController.cs
cv19ResSupportV3/V4/Factories/CaseNotesFactory.cs
cv19ResSupportV3/V4/UseCase/GetCaseNotesByResidentIdUseCase.cs
cv19ResSupportV3/V4/UseCase/Interface/IGetCaseNotesByResidentId.cs

Add get endpoint for resident case notes: GET `/api/v4/residents/{id}/case-notes`
It returns a list of case note objects that look like this:
`{
"Id": 2,
"ResidentId": 1,
"HelpRequestId": 1,
"CaseNote": "content"
}`
CaseNote content currently gets stored in 3 different ways:
1. Old JSON string (one entry contains an array of case notes), for example:
`{"CaseNote": "[
{\"author\":\"Author\",\"noteDate\":\"Tue, 08 Sep 2020 10:15:52 GMT\",\"note\":\"*** TEST ***\"}"}, {\"author\":\"Author\",\"noteDate\":\"Tue, 08 Sep 2020 10:15:52 GMT\",\"note\":\"*** TEST ***\"}"}]`
2. Old non JSON string (one entry can contain multiple notes separated by dashes (--)), for example:
`{ "CaseNote": "Joe Bloggs : Tue, 19 Jan 2021 16:12:22 GMT\n------------\nSome additional case note\n------\n\n\nsmt"}`
3. And …

Get case notes by resident

---

cv19ResSupportV3.Tests/V3/Gateways/CaseNotesGatewayTest.cs
cv19ResSupportV3.Tests/V4/Controllers/CaseNotesControllerTests.cs
cv19ResSupportV3.Tests/V4/E2ETests/GetCaseNotesByHelpRequestId.cs
cv19ResSupportV3.Tests/V4/UseCases/GetCaseNotesByHelpRequestIdUseCaseTests.cs
cv19ResSupportV3/Startup.cs
cv19ResSupportV3/V3/Gateways/CaseNotesGateway.cs
cv19ResSupportV3/V3/Gateways/ICaseNotesGateway.cs
cv19ResSupportV3/V4/Controllers/CaseNotesController.cs
cv19ResSupportV3/V4/UseCase/GetCaseNotesByHelpRequestIdUseCase.cs
cv19ResSupportV3/V4/UseCase/GetCaseNotesByResidentIdUseCase.cs
cv19ResSupportV3/V4/UseCase/Interface/IGetCaseNotesByHelpRequestIdUseCase.cs
cv19ResSupportV3/V4/UseCase/Interface/IGetCaseNotesByResidentIdUseCase.cs

Add get endpoint for help request case notes: GET `/api/v4/residents/{id}/help-requests/{help-request-id}/case-notes`
TL;DR works exactly the same as get case notes by resident ID, but for specific case notes
It returns a list of case note objects that look like this:
`{
"Id": 2,
"ResidentId": 1,
"HelpRequestId": 1,
"CaseNote": "content"
}`
CaseNote content currently gets stored in 3 different ways:
1. Old JSON string (one entry contains an array of case notes), for example:
`{"CaseNote": "[
{\"author\":\"Author\",\"noteDate\":\"Tue, 08 Sep 2020 10:15:52 GMT\",\"note\":\"*** TEST ***\"}"}, {\"author\":\"Author\",\"noteDate\":\"Tue, 08 Sep 2020 10:15:52 GMT\",\"note\":\"*** TEST ***\"}"}]`
2. Old non JSON string (one entry can contain multiple notes separated by dashes (--)), for example: …

Get case notes by help request

---

cv19ResSupportV3.Tests/V4/Controllers/ResidentsControllerTests.cs
cv19ResSupportV3/Startup.cs
cv19ResSupportV3/V4/Controllers/ResidentsController.cs

Replace V4 create resident Use case with V3
Because V4 create resident is not deduplicating residents
seems like currently V4 endpoint was only used from the new UI

Replace V4 create resident Use case with V3

---

cv19ResSupportV3.Tests/V3/E2ETests/CreateHelpRequest.cs
cv19ResSupportV3.Tests/V3/Gateways/CaseNotesGatewayTest.cs
cv19ResSupportV3.Tests/V3/UseCase/CreateCaseNoteUseCaseTests.cs
cv19ResSupportV3.Tests/V3/UseCase/CreateResidentAndHelpRequestUseCaseTest.cs
cv19ResSupportV3.Tests/V4/Controllers/CaseNotesControllerTests.cs
cv19ResSupportV3/V3/Gateways/CaseNotesGateway.cs
cv19ResSupportV3/V3/Gateways/ICaseNotesGateway.cs
cv19ResSupportV3/V3/UseCase/CreateCaseNoteUseCase.cs
cv19ResSupportV3/V3/UseCase/CreateResidentAndHelpRequestUseCase.cs
cv19ResSupportV3/V3/UseCase/Interfaces/ICreateCaseNoteUseCase.cs
cv19ResSupportV3/V4/Controllers/CaseNotesController.cs

- Update the create help request use case in the controller to accept the parameters in the correct order 
- Previously, the incorrect parameters were passed into the execute method of the CreateCaseNote use-case in the controller. ResidentId was passed in place of HelpRequestId and vice versa
na
n/a
The frontend will also need to be fixed as it was the only place this endpoint was being used. These two should be released in parallel.

Update parameter positions of execute method in the CreateCaseNote controller

---

.editorconfig
cv19ResSupportV3.Tests/V3/Gateways/ResidentGatewayTest.cs
cv19ResSupportV3.Tests/V4/E2ETests/SearchResidents.cs
cv19ResSupportV3.Tests/V4/Helpers/PredicatesTests.cs
cv19ResSupportV3.Tests/V4/TestHelpers/EntityHelpers.cs
cv19ResSupportV3.Tests/cv19ResSupportV3.Tests.csproj
cv19ResSupportV3/V3/Domain/Commands/FindResident.cs
cv19ResSupportV3/V3/Factories/Commands/FindResidentFactory.cs
cv19ResSupportV3/V3/Gateways/ResidentGateway.cs
cv19ResSupportV3/V4/Helpers/PredicateHelpers.cs
cv19ResSupportV3/cv19ResSupportV3.csproj

- When first name, last name or both are missing the code won't proceed to Uprn & Dob matching rules.
- All 3 of the Date of birth parts (Year, Month, Day) are required for the Dob rule to flag resident as duplicate. (Previously it was 1+)
- More extensive check for empty values. Previously it was just a "null" check, now it also checks for empty and whitespace string as well.
- Added NHS number rule for flagging resident as duplicate.
- Minor code tweaks to make it more efficient & readable.
- Deduplication isn't working as expected. It's flagging some residents as duplicate, when they are not. And it's not flagging some as duplicate when they are.
- No screenshot
- Trello card: [107](https://trello.com/c/wkcGQa7x/107-bug-de-duping-on-api-too-aggressive).
- Suppressed the Globalisation …

Find resident deduplication fix

---

cv19ResSupportV3.Tests/V3/Gateways/ResidentGatewayTest.cs
cv19ResSupportV3/V3/Gateways/ResidentGateway.cs

- Made NHS number match rule to ignore different NHS number formatting like: `485 777 3456` vs `4857773456`.
- Made Dob match rule ignore `DobMonth` and `DobDay` number formatting of leading zeros: `03` vs `3`.
- Added a missing test case from previous PR to cover code of matching `DobMonth` field of mixed cases (In case it's specified as word or abbreviation): `Jan`, `dec`, `april`, etc.
- To increase accuracy of resident de-duplication.
Trello: [ticket 135](https://trello.com/c/5q2Y8n3b/135-improve-de-duping-on-api-accuracy).
Did this even though not priority, because I'm away for most of next week, and couldn't pick up anything other that would be small enough for the couple of hours I got today.
**This PR is related to bug** on [ticket …

Increase find resident accuracy

---

cv19ResSupportV3.Tests/V3/E2ETests/UpdateHelpRequest.cs
cv19ResSupportV3.Tests/V3/Gateways/HelpRequestGatewayTests.cs
cv19ResSupportV3.Tests/V3/Helpers/EntityHelpers.cs
cv19ResSupportV3.Tests/V3/UseCase/CreateHelpRequestUseCaseTests.cs
cv19ResSupportV3/V3/Gateways/HelpRequestGateway.cs
cv19ResSupportV3/V3/Gateways/IHelpRequestGateway.cs
cv19ResSupportV3/V3/UseCase/CreateHelpRequestUseCase.cs

Finding an existing help request now also matches by helpNeeded as well as CTAS ID. This means multiple help requests can exist for a single CTAS ID as long as the help required differs.
Added helpNeeded to the gateway call to check if a Help Request exists. Updated unit tests and added a new one for this condition.
We're adding a new ingest type to the HTH ingest that will be calling this API. Without this change, someone could potentially have a help request from another ingest that would prevent the new help request being saved in the system.
N/A
'Here To Help' JIRA ticket HTHD-37

Finding an existing help request now also matches by helpNeeded 

---

cv19ResSupportV3.Tests/V3/Factories/ResidentFactoryTest.cs
cv19ResSupportV3.Tests/V3/Gateways/ResidentGatewayTest.cs
cv19ResSupportV3/V3/Domain/Commands/CreateResident.cs
cv19ResSupportV3/V3/Domain/Commands/FindResident.cs
cv19ResSupportV3/V3/Factories/Commands/CreateResidentFactory.cs
cv19ResSupportV3/V3/Factories/Commands/FindResidentFactory.cs
cv19ResSupportV3/V3/Gateways/ResidentGateway.cs

- Added NhsCtasId de-duplication rule.
- Added Email Address de-duplication rule.
- Added Mobile number de-duplication rule.
- Added Landline number de-duplication rule.
- Ensured the checks are made in trim&case-insensitive way where needed.
- Single Phone number is checked against both fields.
- There are still a few records coming in through data ingestion process that do not have enough information for them to be identifiable.
Jira Ticket: [39](https://hackney.atlassian.net/secure/RapidBoard.jspa?rapidView=64&projectKey=HTHD&modal=detail&selectedIssue=HTHD-39).
Couldn't reduce the size of the implementation code further in this time frame, because C# and EF Core are poorly programmed. To give examples:
- Predicate<T\> is the same thing as Func<T, bool>, yet they're made to function …

Added more Resident de-duplication rules.

---

cv19ResSupportV3/V3/Gateways/HelpRequestGateway.cs
cv19ResSupportV3/V3/Gateways/IHelpRequestGateway.cs
cv19ResSupportV3/V3/UseCase/CreateHelpRequestUseCase.cs

Added the ability to prevent an ingest creating a duplicate help request for a resident by applying a generic ingest id. This will be set to the help request type at present.
Without this, every time a generic ingest is run for 'EUSS' help requests, it will create duplicate requests against a resident. By setting the generic ingest id to 'euss' we prevent duplicates, and can remove/make unique for any types that require multiple.

Prevent duplicate generic help types

---

database/Dockerfile

Updated the version of postgres in the dockerfile
The old version seemed to be causing issues with the circleci test and this is a suggested workaround
https://hackney.atlassian.net/browse/HTHD-102

Update postgress version in dockerfile

---

cv19ResSupportV3/V3/Gateways/CaseNotesGateway.cs

Added help needed to the response from create case notes.
This response is consumed by the ingest and the null value for helpNeeded caused a background error. It was decided it's better to populate the full object in the return rather than remove the parsing error as it provides more data to validate.
The helpNeeded was added to case notes object to allow this data to be filtered by the a specific help type.

Added help needed to the return object from create case note.

---

README.md
cv19ResSupportV3.Tests/ConnectionString.cs
cv19ResSupportV3/Startup.cs
cv19ResSupportV3/appsettings.Development.json

- Updated Readme to include Entity Framework migrations and setup required to achieve:
1.  Debug in VS (make serve doesn't get you to breakpoints).
2. All tests pass, including database-connected tests.
The existing Readme got to the point of building but not debugging, and it wasn't clear how to get all tests successfully running against a local database.
- Changed local connection string implementation to avoid having to create environment variables locally (has issues on MacBook).
- Removed steps no longer needed from Readme.

Readme update incl. removing manual steps.

---

cv19ResSupportV3/Startup.cs

It will now always check the environment variable first, as some people may be using this already. This will also ensure any CircleCI / dev environments that use it function. The appSetting value is then a backup for DEBUG environments that do not have an environment variable available.

Change dev connection string implementation:

---

cv19ResSupportV3.Tests/V3/Gateways/ResidentGatewayTest.cs
cv19ResSupportV3/V3/Controllers/HelpRequestCallController.cs
cv19ResSupportV3/V3/Controllers/HelpRequestsController.cs
cv19ResSupportV3/V3/Gateways/HelpRequestGateway.cs
cv19ResSupportV3/V3/Gateways/ResidentGateway.cs
cv19ResSupportV3/V4/Controllers/CaseNotesController.cs
cv19ResSupportV3/V4/Controllers/ResidentHelpRequestsController.cs
cv19ResSupportV3/V4/Controllers/ResidentsController.cs

- Changes to prevent application from crashing when encountering null Nhs Ctas Ids within the database while deduplicating residents.
- Automatic formatting changes with a bit of manual intervention that are likely coming from updated linter.
- So that every resident could be ingested via H2H ingestion process, regardless of what value were historically set within the database. 
- This branch was rebased from master to development, hence, the rewriting of history. This will be related to #145 later down the merge line when the changes will be changed from dev to master.

Prevent application crash upon encountering unset Nhs Ctas Id fields within the database while deduplicating residents 
